services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: baza_postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: baza_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: baza_rabbitmq
    network_mode: bridge
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: baza
      RABBITMQ_DEFAULT_PASS: baza
    restart: unless-stopped
