services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: baza_postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: baza_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped