services:
  minio:
    image: minio/minio:latest
    container_name: baza_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: unless-stopped
    network_mode: bridge

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: bridge
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg17
    container_name: baza_postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: baza_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped