spring.application.name=baza

app.telegram.token=${TELEGRAM_TOKEN}
app.telegram.url=https://api.telegram.org/bot
app.telegram.update-listener-sleep=1s

server.port=8080

spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=all-minilm
spring.ai.ollama.chat.options.model=moondream


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://localhost:5432/baza_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE